apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: replica-set
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: replicaset
          image: httpd:latest
