---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod1
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
...

---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod2
spec:
  containers:
  - name: tomcat
    image: tomcat
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
...