apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rollingupdate
  labels:
    env: prod
spec:
  replicas: 4
  strategy:    
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: rollingupdate
          image: tomcat

