apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpd-container
      image: httpd
      resources:
       limits:
         memory: "128Mi" 
         cpu: "1"
